In [3]:
import pandas as pd
from  pathlib import Path
import importlib as plt
import matplotlib.pyplot as plt
import seaborn as sns

# 3 Datasets
- Client Profiles (df_final_demo): Demographics like age, gender, and account details of our clients.
- Digital Footprints (df_final_web_data): A detailed trace of client interactions online, divided into two parts: pt_1 and pt_2.
- Experiment Roster (df_final_experiment_clients): A list revealing which clients were part of the grand experiment.
- Project Phases & Tasks

In [7]:
client_profiles = pd.read_csv(r"C:\Users\glint\OneDrive\Documents\Ironhack lessons\Project_Vanguard\df_final_demo.csv.txt")
web_data_pt1 = pd.read_csv(r"C:\Users\glint\OneDrive\Documents\Ironhack lessons\Project_Vanguard\df_final_web_data_pt_1.csv.txt")
web_data_pt2 = pd.read_csv(r"C:\Users\glint\OneDrive\Documents\Ironhack lessons\Project_Vanguard\df_final_web_data_pt_2.csv.txt")
experiment_clients = pd.read_csv(r"C:\Users\glint\OneDrive\Documents\Ironhack lessons\Project_Vanguard\df_final_experiment_clients.csv.txt")

In [9]:
client_profiles.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [11]:
experiment_clients.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [14]:
web_data = pd.concat([web_data_pt1, web_data_pt2])
web_data.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [16]:
print(f"Shape: {client_profiles.shape}")

Shape: (70609, 9)

In [21]:
print("Null counts:")
print(client_profiles.isnull().sum())
print(f"\nNull percentages:")
print((client_profiles.isnull().sum() / len(client_profiles) * 100).round(1))

Null counts:
client_id            0
clnt_tenure_yr      14
clnt_tenure_mnth    14
clnt_age            15
gendr               14
num_accts           14
bal                 14
calls_6_mnth        14
logons_6_mnth       14
dtype: int64

Null percentages:
client_id           0.0
clnt_tenure_yr      0.0
clnt_tenure_mnth    0.0
clnt_age            0.0
gendr               0.0
num_accts           0.0
bal                 0.0
calls_6_mnth        0.0
logons_6_mnth       0.0
dtype: float64

In [17]:
print(f"Shape: {experiment_clients}")

Shape:        client_id Variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
70604    2443347       NaN
70605    8788427       NaN
70606     266828       NaN
70607    1266421       NaN
70608    9895983       NaN

[70609 rows x 2 columns]

In [22]:
print("Null counts:")
print(experiment_clients.isnull().sum())
print(f"\nNull percentages:")
print((experiment_clients.isnull().sum() / len(experiment_clients) * 100).round(1))

Null counts:
client_id        0
Variation    20109
dtype: int64

Null percentages:
client_id     0.0
Variation    28.5
dtype: float64

In [36]:
experiment_clients["Variation"].value_counts()["Test"]
print((experiment_clients["Variation"].value_counts()["Test"].sum() / len(experiment_clients) * 100).round(1))

38.2

In [35]:
experiment_clients["Variation"].value_counts()["Control"]
print((experiment_clients["Variation"].value_counts()["Control"].sum() / len(experiment_clients) * 100).round(1))

33.3

In [18]:
print(f"Shape: {web_data}")

Shape:         client_id             visitor_id                      visit_id  \
0         9988021   580560515_7732621733  781255054_21935453173_531117
1         9988021   580560515_7732621733  781255054_21935453173_531117
2         9988021   580560515_7732621733  781255054_21935453173_531117
3         9988021   580560515_7732621733  781255054_21935453173_531117
4         9988021   580560515_7732621733  781255054_21935453173_531117
...           ...                    ...                           ...
412259    9668240   388766751_9038881013   922267647_3096648104_968866
412260    9668240   388766751_9038881013   922267647_3096648104_968866
412261    9668240   388766751_9038881013   922267647_3096648104_968866
412262    9668240   388766751_9038881013   922267647_3096648104_968866
412263     674799  947159805_81558194550   86152093_47511127657_716022

       process_step            date_time
0            step_3  2017-04-17 15:27:07
1            step_2  2017-04-17 15:26:51
2            step_3  2017-04-17 15:19:22
3            step_2  2017-04-17 15:19:13
4            step_3  2017-04-17 15:18:04
...             ...                  ...
412259        start  2017-05-24 18:46:10
412260        start  2017-05-24 18:45:29
412261       step_1  2017-05-24 18:44:51
412262        start  2017-05-24 18:44:34
412263        start  2017-06-03 12:17:09

[755405 rows x 5 columns]

In [23]:
print("Null counts:")
print(web_data.isnull().sum())
print(f"\nNull percentages:")
print((web_data.isnull().sum() / len(web_data) * 100).round(1))

Null counts:
client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

Null percentages:
client_id       0.0
visitor_id      0.0
visit_id        0.0
process_step    0.0
date_time       0.0
dtype: float64